name: Build & Deploy Jupyter Book

on:
  push:
    branches:
      - main  # Adjust this to your default branch if it's different

jobs:
  docs:
    name: Build & deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build book
        run: |
          jupyter-book build docs

      - name: Debug - List files
        run: |
          ls -la
          ls -la docs/_build/html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
